---
kind: pipeline
type: kubernetes
name: default

# remove this section if your CPU is amd64
platform:
  os: linux
  arch: arm64

steps:
  # Step 1
  - name: ensure nexus is available
    image: alpine
    pull: if-not-exists
    commands:
      - apk update
      - apk add curl bash
      - if [ "$(curl -o /dev/null -s -w '%{http_code}' $MAVEN_MIRROR_URL )" = "200" ]; then exit 0; else exit 1; fi
    environment:
       MAVEN_MIRROR_URL:
          from_secret: maven_mirror_url
  # Step 2
  - name: java-build
    image: kameshsampath/drone-java-maven-plugin:v1.0.3
    pull: if-not-exists
    settings:
      maven_mirror_url:
        from_secret: maven_mirror_url
      goals:
        - -DskipTests
        - clean
        - install
          

trigger:
  branch:
  - main

host_aliases:
 - ip: 10.96.137.81
   hostnames:
     - gitea-127.0.0.1.sslip.io