---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: preview
  source: redhat-operators
  name: openshift-pipelines-operator-rh
  sourceNamespace: openshift-marketplace
